version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./Backend/
    ports:
      - "4000:4000"
    volumes:
      - ./Backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./Frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/usr/src/app
    depends_on:
      - backend